language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t craigdurant2001/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true craigdurant2001/docker-react npm run test
